Play with java and maven #0

diff --git a/.github/workflows/misc--latest-info.yml b/.github/workflows/misc--latest-info.yml
--- a/.github/workflows/misc--latest-info.yml
+++ b/.github/workflows/misc--latest-info.yml
@@ -38,3 +38,15 @@ jobs:
         run: ls -laxo ${{ github.workspace }}
       - name: ./.github/scripts/dump-env.sh
         run: ${{ github.workspace }}/.github/scripts/dump-env.sh
+      - name: which java
+        run: >
+          which java || echo "Last Error Code: $?"
+      - name: java --version
+        run: >
+          java --version || echo "Last Error Code: $?"
+      - name: which mvn
+        run: >
+          which mvn || echo "Last Error Code: $?"
+      - name: mvn --version
+        run: >
+          mvn --version || echo "Last Error Code: $?"
